Kotlin. Homework #2. Task #1
alexdtat/shallowSizeTemplate pull request #1
Opened 2022-04-20 20:11 UTC by alexdtat

The solution has been added.

2022-04-20 20:56 UTC, alexdtat commented
Дедлайн, конечно, просрочил, но можно хотя бы не на оценку ревью? Чтобы тему закрепить. :)

2022-04-24 14:33 UTC, illided requested changes
Лучше поздно чем никогда :)
Мне понравилось, мелкие замечания

2022-04-24 14:33 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                            |       throw NotImplementedError("shallowSize function should be implemented")
Вкусовщина возможно, но я бы здесь поменял на что то более понятное конечному пользователю.
Что то типо: данная функция не должна находиться в таком виде и должна была быть заменена позже. А то сейчас пользователь может подумать что это он должен этот метод имплементировать

2022-04-24 14:33 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +fun IrSimpleFunction.isShallowSizeFunction(): Boolean {
Вот здесь можно просто через равно написать.
Детект кажется даже должен это ругать

2022-05-02 09:49 UTC, nbirillo approved these changes

2022-05-02 09:49 UTC, merged